### ISSUE TITLE
此项目的作用？

### ISSUE THREAD

**Issue by AlbertZhaoz** [yangzhongke/NetAutoGUI#1]
杨老师，这个项目是用来干什么的，Readme文件里面没有写。

**Comment by yangzhongke** [comment]
还没弄完，所以就没写readme。
这是把Python版本的PyAutoGUI迁移到.net

**Comment by AlbertZhaoz** [comment]
> 还没弄完，所以就没写readme。 这是把Python版本的PyAutoGUI迁移到.net

好滴，期待ing.
