### ISSUE TITLE
屏幕分辨率大于1920*1080找不到目标

### ISSUE THREAD

**Issue by Mark-Echo** [yangzhongke/NetAutoGUI#10]
老师您好，屏幕分辨率大于1920*1080找不到目标

**Comment by MaMouRenX** [comment]
![QQ截图20240117183506](https://github.com/yangzhongke/NetAutoGUI/assets/49935173/4f2cb510-7bec-4cf7-ba24-e3c17ea26fc6)
模板图片
![发布_1 5](https://github.com/yangzhongke/NetAutoGUI/assets/49935173/0cc1a70b-c61a-4071-af62-ee21b186d27f)
目标图片
