### ISSUE TITLE
希望能定位最满足条件的区域

### ISSUE THREAD

**Issue by qiang-l** [yangzhongke/NetAutoGUI#11]
B站视频中提到的Locate方法，实际上是不能定位最满足条件的区域。（各方法中好像没有按照confidence倒序排列的）
能否提供新的方法或者修改Locate，以实现这一点。

**Comment by yangzhongke** [comment]
谢谢建议。IScreenshotController中增加了一个LocateAllWithConfidence‎方法，请升级到最新版。
