### ISSUE TITLE
屏幕找图时，能否过滤透明色。

### ISSUE THREAD

**Issue by xukai19941231** [yangzhongke/NetAutoGUI#13]
当图片四个坐标角颜色一致时，该颜色视为透明色。
这样比较的时候能减少运算，准确率也会有所提高。

**Comment by yangzhongke** [comment]
抱歉，没明白您的建议，能详细说一下吗

**Comment by xukai19941231** [comment]
> 抱歉，没明白您的建议，能详细说一下吗

就是图片四个角点的颜色rgb值相同时，不比较图片中的所有该颜色。

**Comment by yangzhongke** [comment]
谢谢，目前的比较方法更科学。
