### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Luguangtian** [yangzhongke/NetAutoGUI#15]
![image](https://github.com/yangzhongke/NetAutoGUI/assets/116794681/61b6c3a0-0997-400e-b0ae-2a48ea0aff7d)
为什么直接引用调用方法会报：System.TypeInitializationException:“The type initializer for 'NetAutoGUI.GUI' threw an exception.”
而用控制台test又能成功调用，或者在Program：程序窗体打开之前也能正常调用，    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            NetAutoGUI.Window win = GUI.Application.FindWindowLikeTitle("*edge*");//拿到对应软件的窗体
            win.Activate();//激活
            win.Maximize();//最大化
            ApplicationConfiguration.Initialize();
            Application.Run(new Main());
        }
    }
用在其他地方的时候就是会报错

**Comment by yangzhongke** [comment]
之前的旧版只能在控制台程序中使用，新版已经支持窗口程序。请更新到最新版。

**Comment by Luguangtian** [comment]
enxiexie
