### ISSUE TITLE
关于另一个python 项目 pywinauto

### ISSUE THREAD

**Issue by YDTrade** [yangzhongke/NetAutoGUI#2]
杨老师，pywinauto对比autogui，是不是稳定新和准确都更好点？有没有考虑实现pywinauto的.NET版本？

**Comment by yangzhongke** [comment]
谢谢建议，我会把他们好的东西都融合进来

**Comment by YDTrade** [comment]
> 谢谢建议，我会把他们好的东西都融合进来

期待大佬的实现
