### ISSUE TITLE
Can you help with the sources?)

### ISSUE THREAD

**Issue by RINCODER** [yangzhongke/NetAutoGUI#3]
Hi, I've been using your library for more than two months, but I wanted to improve the program and got stuck due to the fact that I don't want to use the path to the file and make a screenshot of a certain window, can you help with the source of the template search, you have this function written as a GUI.Screenshot.LocateOnScreen, I will be very grateful if you help, because I can't write the recognition system myself or I'm Googling incorrectly

I hope for a positive response

(translated from the translator, there may be errors)

**Comment by yangzhongke** [comment]
Sorry, I didn't understand what you said. Could you be more specific?

**Comment by RINCODER** [comment]
Can you send the code that is responsible for recognizing the object on the screen? In particular, this is the method I used GUI.Screenshot.Locate On Screen

I will be grateful

**Comment by yangzhongke** [comment]
This project is open-source. 
 You can check it below:

https://github.com/yangzhongke/NetAutoGUI/blob/main/NetAutoGUI/Internals/AbstractScreenshotController.cs

**Comment by RINCODER** [comment]
and third-party libraries are used here, I didn't understand?)

**Comment by yangzhongke** [comment]
MatchTemplate is provided by OpenCVSharp.
You can check resources online about it.

**Comment by RINCODER** [comment]
Do I understand correctly that this code and OpenCvSharp will be enough to recognize the image?

**Comment by yangzhongke** [comment]
I think so.

**Comment by RINCODER** [comment]
Thanks very much
