### ISSUE TITLE
杨老师，是否可以增加获取窗口的内容

### ISSUE THREAD

**Issue by azrng** [yangzhongke/NetAutoGUI#5]
举例如  FlaUI框架的
wxWindow.FindAllDescendants();
通过该方法可以获取到该窗口上的内容

或者当前该框架是否可以有啥方法获取到窗口的内容？

**Comment by yangzhongke** [comment]
谢谢，我没打算把他做成一个大而全的工具。既然已经有了成熟的FlatUI，就继续用它就行了。

**Comment by azrng** [comment]
好的，另外提一句  工具很好用，多谢杨老师
