### ISSUE TITLE
电脑连接多个显示器，无法找到其它显示器上的内容

### ISSUE THREAD

**Issue by Mark-Echo** [yangzhongke/NetAutoGUI#7]
老师您好，现在有个问题电脑连接多个显示器，无法找到其它显示器上的内容

**Comment by yangzhongke** [comment]
升级了一下代码，支持多显示器了。
在LocateAllOnScreen等方法中都增加了一个名字叫screenIndex的参数，用来指定显示器的序号。
在进行鼠标操作的时候，需要进行多屏幕的窗口的坐标转换，详细了解[https://stackoverflow.com/questions/53012896/using-setwindowpos-with-multiple-monitors](https://stackoverflow.com/questions/53012896/using-setwindowpos-with-multiple-monitors)

**Comment by Mark-Echo** [comment]
谢谢老师
