### ISSUE TITLE
屏幕缩放100%可以找到按钮，更换成其它缩放比例就会导致按钮找不到

### ISSUE THREAD

**Issue by Mark-Echo** [yangzhongke/NetAutoGUI#9]
老师您好，屏幕缩放100%可以找到按钮，更换成其它缩放比例就会导致按钮找不到。将需要找的按钮图片替换为对应的缩放比例也找不到。

**Comment by yangzhongke** [comment]
把要找的按钮在对应缩放比例下截图也匹配不到吗？

**Comment by Mark-Echo** [comment]
是的老师，试了好多次都不行

**Comment by yangzhongke** [comment]
我这里无法重现，你能提供截图图片和待匹配内容的图片（都需要是同样缩放比例下）吗？

**Comment by Mark-Echo** [comment]
已解决，获取当前屏幕的缩放比例后截图在查找才是在真实的分辨率图片上查找
![image](https://github.com/yangzhongke/NetAutoGUI/assets/49935173/15b69d26-5b7d-4125-a408-7203ebf5e144)
